### PR TITLE
ensure CarMultihashIterator sorts CIDs by offset

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by mvdan** [comment]
FYI @masih, Andrew correctly spotted a source of non-determinism when building IPLD nodes. Details in the commit message. This completely butchers our API decisions with the context etc, see the TODOs :) We can talk about it on Monday. This is a quick fix to unblock Andrew in the meantime.

**Review by gammazero — APPROVED** [review]
LGTM. This is probably more than a quick fix as it should ultimately be the provider's responsibility to ensure deterministic CAR iteration.

**Comment by mvdan** [comment]
I agree that this approach is likely what we want anyway, long-term. The "quick fix" part is how the current API for loading the index no longer makes much sense :) I've left TODOs around that. Masih and I can discuss it tomorrow, and probably simplify it somewhat.

I'll merge for now, to just make the main branch work reliably sooner than later.

**Comment by masih** [comment]
I see so the point is global determinism across all indices vs local determinism among indices of same type.

**Pull request merged**
